  - name: add hostname to /etc/hosts
    vars:
      comment: '# added by ansible'
    lineinfile:
      dest: /etc/hosts
      regexp: "127[.]0[.]0[.]1.*"
      line: "127.0.0.1 localhost.localdomain localhost {{ ansible_hostname }} {{ comment }}"
      state: present
      backup: yes

  - name: add IP address of all hosts to /etc/hosts
    vars:
      comment: '# added by ansible'
    lineinfile:
      dest: /etc/hosts
      regexp: ".* {{ item }} {{ comment }}"
      line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }} {{ item }} {{ comment }}"
      state: present
      backup: yes
    when: ansible_hostname != item
    loop: "{{ query('inventory_hostnames', 'all') }}"

  - name: add docker registry to hosts
    lineinfile:
      dest: /etc/hosts
      regexp: ".* docker.artifactory.ravn.imanage.com"
      line: "165.193.189.40 docker.artifactory.ravn.imanage.com"
      state: present
      backup: yes

  - name: update dns
    copy:
      src: resolv.conf
      dest: /etc/resolv.conf
      owner: root
      group: root
      mode: '0644'

  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Ensure docker group exists
    group:
      name: docker
      state: present

  - name: Add ansible user
    user:
      name: ansible
      comment: Ansible
      shell: /bin/bash
      groups: wheel,docker
      password: "{{ password }}"
      append: yes

  - name: Allow wheel group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: '/usr/sbin/visudo -cf %s'

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Disable SELinux-file
    replace:
      path: /etc/sysconfig/selinux
      regexp: '^SELINUX=enforcing'
      replace: 'SELINUX=disabled'

  - name: Install Docker dependencies
    yum:
      name:
       - yum-utils
       - device-mapper-persistent-data
       - lvm2
      state: present

  - name: Copy Docker repo
    copy:
      src: ./files/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
      owner: root
      group: root
      mode: '0644'

  - name: upgrade installation
    yum:
      name: '*'
      state: latest

  - name: Install Docker-CE
    yum:
      name: docker-ce
      state: present

  - name: Ensure docker config folder exists
    file:
      path: /etc/docker
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Configure Docker for insecure RAVN repo
    copy:
      src: ./files/daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'

  - name: Enable Docker service
    service:
      name: docker
      enabled: yes

  - name: Start Docker service
    service:
      name: docker
      state: started

  - name: Ensure docker group exists
    group:
      name: docker
      state: present

  - name: Stop firewalld service
    service:
      name: firewalld
      state: stopped

  - name: Disable firewalld service
    service:
      name: firewalld
      enabled: no

  - name: Disable swap
    replace:
      path: /etc/fstab
      regexp: '^/dev/mapper/centos-swap'
      replace: '# /dev/mapper/centos-swap'

  - name: Stop swap
    shell: swapoff -a

  - name: Check if ansible home exists
    stat:
      path: /root/prep.flag
    register: prep_run

  - name: Create flag file
    file:
      path: /root/prep.flag
      state: touch

  - name: Reboot server
    command:
      /sbin/shutdown -r -t 4
    when: not prep_run.stat.exists
